[package]
name = "suit-up-repos/roblox-blitz"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Core
Knit = "sleitnick/knit@1.7.0"
Signal = "sleitnick/signal@2.0.1"
Sequence = "endarke/sequence@1.4.0"
Dumpster = "kinqandi/dumpster@0.3.8"
Promise = "evaera/promise@4.0.0"

[dev-dependencies]
ProfileService = "rudy-dev/profileservice@1.0.0"
GameAnalytics = "gameanalytics/gameanalytics-sdk@2.2.4"